### ISSUE TITLE
Identify project data and describe analysis goals

### ISSUE THREAD

**Issue by Shakkour726** [ds4owd-001/project_Shakkour726#1]
@larnsce @mianzg @sskorik01, thanks!

**Comment by larnsce** [comment]
Thank you, @Shakkour726. It’s all set up as required and your data and analysis goals sound exciting.

I have one task for you:

1. Please rename your repository to `project-shakkour726`. You can do that here: https://github.com/ds4owd-001/project_Shakkour726/settings
2. Let me know when you are done by responding to this comment.

You can start working with your data and open a new issue on this repository if you have questions or face problems. Please tag us when you open the issue.
