### ISSUE TITLE
Capstone project submission - Producing JMP estimates

### ISSUE THREAD

**Issue by Shakkour726** [ds4owd-001/project_Shakkour726#2]
Dear @larnsce @mianzg @sskorik01,

Apologies for the late submission! please let me know if you have any comments.

Kindest regards,
Shakkour

**Comment by mianzg** [comment]
Hi @Shakkour726 congrats on submitting the project! I marked this submission in our log. We are currently reaching our capacities so the feedbacks will be given at a later date. Thanks for participating in the course and I hope you enjoyed it.
